export const LOAD_PRS_SUCCESS = 'LOAD_PRS_SUCCESS';  
export const ADD_PR_SUCCESS = 'ADD_PR_SUCCESS';
export const DELETE_PR_SUCCESS = 'DELETE_PR_SUCCESS';
export const UPDATE_PR_SUCCESS = 'UPDATE_PR_SUCCESS';
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS';  
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';